// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whsxgofhinunbcotwnro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indoc3hnb2ZoaW51bmJjb3R3bnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNDg1NjMsImV4cCI6MjA4ODkyNDU2M30.YHnrbQtKjUj6JMa37CMzWgoYrXZLNz44ZxSD7JjD1lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});